name: release

on: 
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${GITHUB_REF_NAME}.zip ${{ github.event.repository.name }} -r  -x "*/.git/*" -x "*/.github/*" -x "*/.git"

      - uses:  ncipollo/release-action@v1
        with:
          tag: '${{ github.ref_name }}'
          artifacts: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          allowUpdates: true
          artifactErrorsFailBuild: true
          bodyFile: CHANGELOG.md
